import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
import {
  formatPolicyDate,
  legalPageMetadata,
  legalPolicyVersions,
} from "@/lib/legal";

const description =
  "Privacy Policy for Francois Consulting Group and The Human Capacity Summit.";

export const metadata: Metadata = legalPageMetadata({
  description,
  route: legalPolicyVersions.privacy.route,
  title: legalPolicyVersions.privacy.title,
});

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effectiveDate={formatPolicyDate(legalPolicyVersions.privacy.effectiveDate)}
      lastUpdated={formatPolicyDate(legalPolicyVersions.privacy.lastUpdated)}
    >
      <section>
        <h2>1. Who this policy applies to</h2>
        <p>
          This Privacy Policy explains how Francois Consulting Group handles personal
          information collected through this website, including The Human Capacity Summit
          registration flow, contact enquiries, and program enquiry forms.
        </p>
      </section>

      <section>
        <h2>2. Privacy contact</h2>
        <p>
          If you have questions about this policy or about how your information is handled, please
          contact us at hello@francoisconsultinggroup.com.
        </p>
      </section>

      <section>
        <h2>3. Information we collect</h2>
        <ul>
          <li>
            Summit registration details such as first name, last name, email address,
            telephone number, country, organisation, role, attendee count, submitted notes,
            and any accessibility or dietary information provided.
          </li>
          <li>
            Contact and enquiry form details such as name, email address, telephone number,
            organisation, selected program package, team size, and message content.
          </li>
          <li>
            Transaction records connected with Summit registration, including payment status,
            payment method, currency, amount due, payment reference, PayPal order ID, capture ID,
            payer email, reconciliation records, verification timestamps, refund records, and
            related operational audit history.
          </li>
          <li>
            Technical and hosting information that may arise from server logs or platform
            operations, such as IP address, browser, device, and request metadata, only to
            the extent those records are generated by the hosting or payment infrastructure.
          </li>
        </ul>
      </section>

      <section>
        <h2>4. How information is collected</h2>
        <ul>
          <li>Directly from forms you complete on this website.</li>
          <li>From PayPal when a Summit payment is approved, captured, reversed, or refunded.</li>
          <li>
            From authorised administrative review when a Direct Bank Transfer is checked,
            reconciled, verified, marked under review, or marked expired.
          </li>
          <li>From website, hosting, and security logs generated during normal operation.</li>
        </ul>
      </section>

      <section>
        <h2>5. Why we use personal information</h2>
        <ul>
          <li>To process event registrations and maintain attendee records.</li>
          <li>To create, verify, capture, reconcile, or review Summit payments.</li>
          <li>To issue bank-transfer instructions and reconcile bank-transfer references.</li>
          <li>To send confirmations and essential event or service-related updates.</li>
          <li>To respond to enquiries and follow up on service requests.</li>
          <li>To prevent fraud, spam, abuse, and security incidents.</li>
          <li>To meet legal, accounting, tax, and record-keeping obligations.</li>
        </ul>
      </section>

      <section>
        <h2>6. PayPal processing</h2>
        <p>
          Summit payments are processed through PayPal. The site does not directly collect or
          store full card numbers, card security codes, or PayPal login credentials.
        </p>
        <p>
          The site may retain payment-related records such as order IDs, capture IDs, payment
          status, payer email, amount, and associated registration records so registrations can
          be administered and verified.
        </p>
        <p>
          PayPal handles payment and funding data under its own privacy practices. Please review
          PayPal&apos;s privacy materials before using that service.
        </p>
      </section>

      <section>
        <h2>7. Direct Bank Transfer records</h2>
        <p>
          Where Direct Bank Transfer is offered, the site may retain payment-related operational
          records such as the selected payment method, original USD amount, TTD amount due,
          configured fixed exchange rate, payment reference, payment status, payment deadline,
          amount and currency received, bank transaction reference, reconciliation notes, and
          verification timestamps.
        </p>
        <p>
          The website does not collect or store online-banking passwords, security questions, PINs,
          or other customer online-banking login credentials.
        </p>
      </section>

      <section>
        <h2>8. Service providers used in this project</h2>
        <ul>
          <li>PayPal for payment processing.</li>
          <li>Sanity for Summit order storage when configured by the client.</li>
          <li>Resend for outbound transactional website email when configured.</li>
          <li>Vercel hosting and related infrastructure services.</li>
        </ul>
      </section>

      <section>
        <h2>9. International transfers</h2>
        <p>
          Because the project uses cloud infrastructure and third-party processors, personal
          information may be processed or stored outside Trinidad and Tobago, including in the
          jurisdictions where PayPal, Vercel, Resend, or Sanity operate their services.
        </p>
      </section>

      <section>
        <h2>10. Retention</h2>
        <p>
          Registration, payment, enquiry, and operational records are retained for as long as
          reasonably necessary for event administration, customer support, legal compliance,
          accounting, and dispute handling.
        </p>
      </section>

      <section>
        <h2>11. Sharing</h2>
        <p>
          Personal information may be shared with service providers and professional advisers who
          need it for payment processing, hosting, email delivery, operational support, legal
          compliance, or security response. Personal information is not sold.
        </p>
      </section>

      <section>
        <h2>12. Security</h2>
        <p>
          Reasonable technical and organisational measures are used to protect personal
          information, but no website or online transmission can be guaranteed to be completely
          secure.
        </p>
      </section>

      <section>
        <h2>13. Privacy requests</h2>
        <p>
          You may request access to, correction of, or deletion of your personal information by
          contacting the privacy contact listed above. Some records may need to be retained where
          required for payment verification, accounting, legal obligations, or dispute handling.
        </p>
      </section>

      <section>
        <h2>14. Children&apos;s privacy</h2>
        <p>
          This website and Summit are intended for adults and professional participants.
        </p>
      </section>

      <section>
        <h2>15. Cookies and analytics</h2>
        <p>
          Based on the current code audit dated August 6, 2026, no separate analytics package,
          tracking pixel, newsletter tooling, or non-essential cookie banner implementation was
          identified in the repository. Standard technical cookies or logs may still be used by
          core platform services such as hosting and PayPal.
        </p>
      </section>

      <section>
        <h2>16. Third-party links</h2>
        <p>
          This website includes links to third-party services and websites. Their privacy
          practices are governed by their own terms and notices.
        </p>
      </section>

      <section>
        <h2>17. Changes to this policy</h2>
        <p>
          This Privacy Policy may be updated from time to time. Material changes will be posted on
          this page with an updated effective or last-updated date.
        </p>
      </section>

      <section>
        <h2>18. Governing jurisdiction</h2>
        <p>
          This policy is governed by the laws applicable to Francois Consulting Group and its
          operations.
        </p>
      </section>
    </LegalPage>
  );
}
